AWSTemplateFormatVersion: '2010-09-09'
Description: 'template for rds launch'

Parameters:
  cidr:
    Type: String
    Default: 10.0.0.0/16
  subnetcount:
    Type: String
    Default: "4" 
  subnetmask:
    Type: String
    Default: "8"  
Resources:
  rds:
    Type: "AWS::RDS::DBInstance"
    Properties:
      AllocatedStorage: 20
      AllowMajorVersionUpgrade: false
      AutoMinorVersionUpgrade: false
      DBInstanceClass: db.t2.micro #required
      DBInstanceIdentifier: testDB
      DBSubnetGroupName: !Ref subgroupID
      DeleteAutomatedBackups: true  
      DeletionProtection: false
      Engine: MySQL
      EngineVersion: '5.7.22'
      MasterUserPassword: '12345678' 
      MasterUsername: admin
      MultiAZ: false
      PubliclyAccessible: false
      StorageType: Standard
      UseDefaultProcessorFeatures: true
      VPCSecurityGroups:
        - !Ref secGroupName  
############vpc and subnet############
  myVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: deepsvpc
  pubsubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select 
        - 0
        - !GetAZs ""
      MapPublicIpOnLaunch: true
      VpcId: !Ref myVPC
      CidrBlock: !Select [0, !Cidr [!Ref cidr, !Ref subnetcount, !Ref subnetmask]]
      Tags:
        - Key: Name
          Value: Ibex-pub-sub1
  pubsubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select 
        - 1
        - !GetAZs ""
      MapPublicIpOnLaunch: true  
      VpcId: !Ref myVPC
      CidrBlock: !Select [1, !Cidr [!Ref cidr, !Ref subnetcount, !Ref subnetmask]]
      Tags:
        - Key: Name
          Value: Ibex-pub-sub2
 ###########security##########         
  secGroupName:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: security for rds and vpc   
      VpcId: !Ref myVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0  
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: 0.0.0.0/0  
#######subnet group##########
  subgroupID:
    Type: "AWS::RDS::DBSubnetGroup"
    Properties:
      DBSubnetGroupDescription: subnet group for rds #required
      SubnetIds: #required
        - !Ref pubsubnet1
        - !Ref pubsubnet2
#############################
  
